### PR TITLE
Issue/119

### PR DESCRIPTION
**Pull request by pypeaday**
Working on #119 to improve work while `pre-commit` is condiered.

I added `isort` as a check with optional overwriting like `black`.
I added a few `flake8` checks....
`E7` for statement checking. This is motivated by me seeing lots of `if X == None`, not in CrossHair but in general.
`F60` because `F62` doesn't look particularly relevant but there are plenty of `dict` objects floating around and so I figured adding a safety check for keys might make some sense.

I'm not sure what else ought to be added for your workflow, or perhaps just running defaults with some specific checks ignored might make more sense? I'm honestly not sure, looking forward to your thoughts!

### CODE REVIEW

**Comment by nicpayne713** [comment]
Just saw checks fail... Silly me didn't actually run your precommit before pushing! I'll do that later today

**Comment by pschanely** [comment]
Github requires manual CI build approvals for first-time contributors, so it didn't run until just now - no worries!

I haven't looked carefully into the flake8 errors yet. Because CrossHair does some wacky and detailed things, we may need to break style in a few places. For example, the CrossHair is intercepts the isinstance() function and some (but probably not all) of those direct type comparisons may be intentional. Same for explicit checking of boolean values "x is True" etc. I'll need to investigate further. For checks without many violations, one option would be to just mark lines with "# noqa" and I could revisit later.

**Comment by nicpayne713** [comment]
I got a little crazy with the flake8 fixes... probably could have ignored a lot, many are E741 for "ambiguous variable name" but I figured if improvements are on the menu might as well go for as much as possible.

I've left all E712,E721,E722 per your comment about the nature of CrossHair, so maybe they're worth discussing.

I also got rid of `import *` and replaced with explicit imports thanks to `removestar`, if that's a problem it's easily reverted!

Let me know your thoughts - sorry this PR is getting big, I guess in my experience, formatting PRs can get somewhat out of hand really fast...

**Comment by nicpayne713** [comment]
@orsinium I have no idea what conflicts I could be hitting... I am definitely rebased on `master` just fine, or gitkraken is a liar (which I doubt)... so ya, just a bit confused what's going on here.

**Comment by nicpayne713** [comment]
> @orsinium I have no idea what conflicts I could be hitting... I am definitely rebased on `master` just fine, or gitkraken is a liar (which I doubt)... so ya, just a bit confused what's going on here.

I'm an idiot... read the errors you doof...

**Comment by pschanely** [comment]
Hi @nicpayne713 - just checking in!
If you've needed to move on to other things, that's totally fine - would it be cool if I pull this and @orsinium's patches into my own change set?
Just getting anxious because the baseline may have some reorganization soon, and it would be great if we didn't lose this. :)

**Comment by nicpayne713** [comment]
Oh sorry! No, we've been sick over here and I've just lost momentum taking care of my kids and then myself as i caught it as they were getting better. If it's easy for you to pull the changes in then definitely do it (i don't like need the PR or anything), but if you want me to try to get it fixed up tonight i can probably spend some time on it

**Comment by pschanely** [comment]
Oh, I am sorry to hear that; hope you feel better soon!

>  but if you want me to try to get it fixed up tonight i can probably spend some time on it

Oh golly, no it's not that urgent! If you would like to give it a shot in the next week or so, that's super great. I am also fine hacking up my own version too, though, so just LMK however you'd like to proceed!

I'm really grateful for all the time you've contributed already. Thank you.

**Comment by nicpayne713** [comment]
Everyone's recovering, I'm on the tail end but doing ok, thanks!

Tonight was fine just cause I was able to sit down - all I did here was rebase though, resolved the conflicts but I ended up undoing some of my changes wherein I added explicit imports in place of some `import *`. I thought I remembered seeing that done elsewhere? Could've been another project and it's easy enough to redo anyways. Let me know if this is passable!

**Comment by nicpayne713** [comment]
And I just noticed my `.envrc` file got thrown in there.... curse Girkraken's "stage all changes" button... haha, let me know if you want that gone (however, I will say that with `direnv` it's so handy to not have to remember to activate the right virtual environment for my projects)

**Comment by nicpayne713** [comment]
I have a habit of pulling the trigger and then catching a bunch of stuff - I missed @orsinium merge request into my branch here entirely, wait to approve I guess until we know if their changes should get implemented or not!

**Comment by pschanely** [comment]
CI triggered! Yeah, I think I might side on pulling `.envrc` out?
Personally, I am on conda, but I use many different environments for different python versions etc. (I'm actually not super familiar with .envrc - it would persistently try to re-set my conda environment?)

**Comment by orsinium** [comment]
> wait to approve I guess until we know if their changes should get implemented or not!

Yep, they should, the tests fail dramatically without this patch. Mostly, because after renaming `l` argument into `ls`, the contracts still use `l`. And there are a few other small details, like imports from typing that are available only on Python 3.9+ or using `is` where only `==` would work.

**Comment by nicpayne713** [comment]
Thanks for your patience with me on this one guys - we use AZDO at work, I use a lot of GitHub for personal projects at home but that's mostly fork/clone and use - not a lot of collaboration. I also realized our workflow is to always rebase and squash on PR so maybe that's out of the norm? Anyways, @orsinium 's path is in, hopefully these pass and the changes are more helpful than not (ie. using 'ls' instead of 'l' which was just to silence a flake 8 warning)

**Comment by nicpayne713** [comment]
>Personally, I am on conda, but I use many different environments for different python versions etc. (I'm actually not super familiar with .envrc - it would persistently try to re-set my conda environment?)

I am in the middle of switching from conda to venv, but I'm still using a .envrc file just with a different function to do the virtual environment with venv instead of conda. It doesn't persistently do anything, just with `direnv` when you enter into a directory that has a .envrc file, it executes it like a bashrc when you open a login shell. I'm hoping into anywhere from 8 to 12 different repos every day at work and using this makes it easy for me to keep the right environment automatically activated, or when I make a new project I use it right away to ensure I'm pip installing stuff into a virtual environment, the right one, and not the base environment. I'm not sure how to use it super well with different python versions for the same project - git worktrees + envrc might make an elegant solution, one that I"m actually planning on implementing into my workflow at work anyways, which would give you a different envrc for each branch since each branch checked out is its own directory. Anyways, it's gone from here easy - definitely wasn't within scope of this change anyways but for future reference it's a super handy tool!

**Comment by pschanely** [comment]
Oops, never replied about `direnv`: I'll take a tiny step immediately and add `.envrc` to the gitignore, so that we're at least direnv-friendly :)

**Comment by nicpayne713** [comment]
Holy mother of forgotten side work... Sorry for totally ghosting this for months! I'm glad you were able to get at least something merged, hopefully it adds value to CrossHair!

**Pull request merged**
